EXAMPLES_DIR = 'examples/'
WORKSPACE_DIR = 'workspace/'
OUTPUT_DIR = WORKSPACE_DIR + 'out_stl/'
DEFAULT_INPUT_DIR = WORKSPACE_DIR + 'in_png_txt/'

LIBLOUIS_PATH = 'third/liblouis/'
TABLES_PATH = LIBLOUIS_PATH + 'tables/'

DEFAULT_TABLE = 'de-g2.ctb'
BIN_NAME = 'lou_translate'
BIN_PATH_WINDOWS = LIBLOUIS_PATH + BIN_NAME

MAX_WIDTH = 200
MAX_HEIGHT = 200
MAX_DEPTH = 40
